openapi: 3.0.1
info:
  title: ProcesadorEnviosAPI
  version: v1
servers:
  - url: /Prod
paths:
  /api/Envios:
    get:
      tags:
        - Envios
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Envio'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Envio'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Envio'
    post:
      tags:
        - Envios
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Envio'
          text/json:
            schema:
              $ref: '#/components/schemas/Envio'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Envio'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Envio'
            application/json:
              schema:
                $ref: '#/components/schemas/Envio'
            text/json:
              schema:
                $ref: '#/components/schemas/Envio'
  '/api/Envios/{envioId}':
    get:
      tags:
        - Envios
      parameters:
        - name: envioId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Envio'
            application/json:
              schema:
                $ref: '#/components/schemas/Envio'
            text/json:
              schema:
                $ref: '#/components/schemas/Envio'
  '/api/Envios/{envioId}/novedades':
    post:
      tags:
        - Envios
      parameters:
        - name: envioId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Novedades'
          text/json:
            schema:
              $ref: '#/components/schemas/Novedades'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Novedades'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Novedades'
            application/json:
              schema:
                $ref: '#/components/schemas/Novedades'
            text/json:
              schema:
                $ref: '#/components/schemas/Novedades'
  /api/Envios/token:
    get:
      tags:
        - Envios
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
  /api/OperadoresLogisticos:
    get:
      tags:
        - OperadoresLogisticos
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OperadorLogistico'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OperadorLogistico'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OperadorLogistico'
    post:
      tags:
        - OperadoresLogisticos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OperadorLogistico'
          text/json:
            schema:
              $ref: '#/components/schemas/OperadorLogistico'
          application/*+json:
            schema:
              $ref: '#/components/schemas/OperadorLogistico'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/OperadorLogistico'
            application/json:
              schema:
                $ref: '#/components/schemas/OperadorLogistico'
            text/json:
              schema:
                $ref: '#/components/schemas/OperadorLogistico'
  '/api/OperadoresLogisticos/{operadorLogisticoId}':
    get:
      tags:
        - OperadoresLogisticos
      parameters:
        - name: operadorLogisticoId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/OperadorLogistico'
            application/json:
              schema:
                $ref: '#/components/schemas/OperadorLogistico'
            text/json:
              schema:
                $ref: '#/components/schemas/OperadorLogistico'
    delete:
      tags:
        - OperadoresLogisticos
      parameters:
        - name: operadorLogisticoId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  /api/OperadoresLogisticos/token:
    get:
      tags:
        - OperadoresLogisticos
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
components:
  schemas:
    Envio:
      type: object
      properties:
        id:
          type: integer
          format: int32
        direccionOrigen:
          type: string
          nullable: true
        direccionDestino:
          type: string
          nullable: true
        contactoComprador:
          type: string
          nullable: true
        estadoEnvio:
          type: string
          nullable: true
        detalleProducto:
          type: string
          nullable: true
        operadorLogistico:
          type: integer
          format: int32
      additionalProperties: false
    Novedades:
      type: object
      properties:
        id:
          type: integer
          format: int32
        idEnvio:
          type: integer
          format: int32
        nuevoEstado:
          type: string
          nullable: true
      additionalProperties: false
    OperadorLogistico:
      type: object
      properties:
        id:
          type: integer
          format: int32
        nombre:
          type: string
          nullable: true
      additionalProperties: false